# Homework 3
*Edited by Yibang (Christopher) Liu, 8/8*

## Question 1
Read the code below and rewrite it using only numpy functions (without for loop, if-else statements). Benchmark your implementation. How much is it faster than the naive python implementation? (hint: use np.isin)

```python
def func1(names, db):
    idx = []
    for i in names:
        if i in db:
            idx.append(db.index(i))
    return idx
```

In [1]:
import numpy as np

In [2]:
def myfunc1(names, db):
    names = np.array(names)
    db = list(db)
    return np.frompyfunc(db.index, 1, 1)(names[np.isin(names, db)])

In [3]:
# This can also be a substitution of the original function when:
# 1. No repetition occurs in names;
# 2. We don't care about the sequence of the output.
def myfunc2(names, db):
    return np.arange(len(db))[np.isin(db, names)]

In [4]:
def func1(names, db):
    idx = []
    for i in names:
        if i in db:
            idx.append(db.index(i))
    return idx

In [5]:
#Test case 1
names1 = [1,2,3,4,5, 5,4,3,2,1, 1,2,3,4,5]
db1 = [2,5]

print(func1(names1, db1))
print(myfunc1(names1, db1))
print(myfunc2(names1, db1))

[0, 1, 1, 0, 0, 1]
[0 1 1 0 0 1]
[0 1]


In [6]:
#Test case 2
names2 = list(range(1000))
db2 = list(range(500))

%timeit func1(names2, db2)
%timeit myfunc1(names2, db2)
%timeit myfunc2(names2, db2)

5.16 ms ± 29.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.69 ms ± 33.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
140 µs ± 3.93 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Question 2
Use only numpy functions (without for loop, if-else statements) to find the largest 3 distances between points if either points is inside the circle of
raidus r0. Then return these points.

```python
>>> coordinates = np.array(
[[0.968, 0.313],
 [0.692, 0.876],
 [0.895, 0.085],
 [0.039, 0.17 ],
 [0.878, 0.098]]
)
>>> cirle_r0 = 0.9
>>> print(search_pairs(coordinates, cirle_r0))

# The indices of the relevant points in the original coordinates
[[2 1]
 [3 0]
 [3 1]]
```


In [7]:
def search_pairs(coordinates, r0):
    # Distances between every two points.
    pair_dists = np.linalg.norm(coordinates[:, np.newaxis, :] - coordinates, axis = 2)
    # Mask: whether the point is inside the circle.
    points_in_r0 = np.linalg.norm(coordinates, axis = 1) < r0
    # Mask: for every pair of points, whether either point is inside the circle.
    mask_r0 = points_in_r0[:, np.newaxis] ^ points_in_r0
    # Only the lower half of matrices would be used to avoid repetition.
    mask_uniq_dists = np.tril(np.ones_like(mask_r0), k = -1)
    # Masked distances.
    uniq_dists = pair_dists[mask_r0 & mask_uniq_dists]
    # Return the points.
    return np.argwhere(mask_r0 & mask_uniq_dists)[np.argpartition(uniq_dists, -3)[-3:]]

In [8]:
coordinates = np.array(
[[0.968, 0.313],
 [0.692, 0.876],
 [0.895, 0.085],
 [0.039, 0.17 ],
 [0.878, 0.098]]
)
cirle_r0 = 0.9
print(search_pairs(coordinates, cirle_r0))

[[2 1]
 [3 0]
 [3 1]]
